### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by mattkrick** [delta-db/deltadb#30]
I think this whole client-side cache + data transport thing is gonna be the next area to get a bunch of attention & I like the concepts behind deltadb. In the future, I'm hoping socketCluster + deltadb can replace something like deepstream.io while remaining more flexible.
I wanted to get your thoughts on a few things:
- transport? Currently you use polling, but those HTTP headers are really gonna add up, especially when making a whole bunch of tiny changes, like booleans. any plans on opening this up to use websockets?
- redux? I've toyed with using redux as a client-side cache, but haven't built out anything that also uses serviceWorkers. I haven't dug into the SC much, but would it be possible to break out the cache so folks can use plugins to use the cache of their liking? I'm thinking like a delta-redux-plugin that allows me to do `deltaDB.setReduxStore(store)`
- what are your thoughts on webworkers to execute the async fetches?
- have you looked into piggybacking off the inertia of graphQL so users could write graphQL queries for deltadb? See https://github.com/lokka/lokka for an example

Cheers, keep up the good work!

**Comment by redgeoff** [comment]
- There is a really rough Roadmap at https://github.com/delta-db/deltadb-server/wiki/DeltaDB-Roadmap. I’ve added a few items based on your comments. Thanks for the feedback!
- Actually, DeltaDB uses socket.io (web sockets) to exchange data with the server and data is only exchanged when there is a change. There is an area internally in the server code that does “poll” for data using a SQL query, but that is just because I haven’t gotten around to using web sockets within the actual server. I had to take a few shortcuts to get a working version of the software done this century :)
- I have to admit that my experience with the React ecosystem is fairly limited. I quickly took a look at redux js and it looks pretty cool. At the moment, DeltaDB implements a fairly simple pub/sub system using EventEmitters. Perhaps in the future it would be nice to add something more complex.
- I think this could be a great enhancement. Due to the way DeltaDB is written, I think it would do a pretty good job at syncing data while keeping the UI responsive, but I haven’t stress tested this yet. My concern with webworkers would be cross browser support. I have limited experience with webworkers and know that most modern browsers support them, but I’m sure there are a lot of gotchas.
- I think implementing something like graphQL would be awesome! I think this would probably be a project for later and I’d also love to see things like support for elasticsearch.
